import { useState } from "react";
import { ArrowUp } from "lucide-react";
import { Section, SectionHeader, Reveal } from "./Section";
import { Logo } from "./Logo";
import { cn } from "@/lib/utils";

const ANSWERS: Record<string, { answer: string; refs: string[] }> = {
  "Why is my SEO score low?": {
    answer:
      "Your SEO score is primarily affected by metadata duplication and crawl depth. 27 pages share a single description generated by three templates, and /services sits five clicks from the homepage. Core Web Vitals pass everywhere, so this is an architecture problem, not a speed problem.",
    refs: ["seo.metadata.duplicate", "seo.crawl.depth", "seo.canonical.redirect"],
  },
  "Why is my website slow?": {
    answer:
      "It mostly isn't. Median TTFB is 31 ms and desktop LCP is 1.2s. The exception is mobile /pricing at 4.1s, caused by a 1.4 MB PNG hero served at 2400px into a 720px slot. Converting it to AVIF recovers an estimated 1.9s.",
    refs: ["perf.lcp.mobile", "perf.image.oversized"],
  },
  "What should I fix first?": {
    answer:
      "The missing Content-Security-Policy on /app. It's your only critical exposure, it takes one header to ship, and it lifts Security from 96 to 99. Second is the pricing hero image — highest performance gain per hour of work.",
    refs: ["security.csp.missing", "perf.image.oversized"],
  },
  "Is my website secure?": {
    answer:
      "Broadly yes — TLS 1.3, HSTS with preload, a valid chain expiring in 214 days, and no known CVEs in detected libraries. Two gaps: CSP is absent on four route groups, and DMARC is set to p=none, which lets spoofed mail through.",
    refs: ["security.csp.missing", "email.dmarc.policy", "ssl.chain.valid"],
  },
  "How can I improve SEO?": {
    answer:
      "Flatten navigation so /services and /resources are two clicks deep, generate unique descriptions for the 27 templated pages, and repoint the 9 canonicals currently aimed at a 301 target. Modelled impact: +14% on the SEO layer.",
    refs: ["seo.crawl.depth", "seo.metadata.duplicate", "seo.canonical.redirect"],
  },
  "Why is my competitor ranking higher?": {
    answer:
      "Competitor A's category pages are two clicks from their homepage and each carries unique structured data. Their raw performance is worse than yours — they win on information architecture, which is the cheaper of the two things to fix.",
    refs: ["compare.seo.architecture", "compare.perf.delta"],
  },
};

const QUESTIONS = Object.keys(ANSWERS);

export function AskSiteIQ() {
  const [question, setQuestion] = useState(QUESTIONS[0]!);
  const [draft, setDraft] = useState("");
  const current = ANSWERS[question]!;

  return (
    <Section tone="surface">
      <SectionHeader
        eyebrow="Ask SiteIQ"
        title="Ask Your Website Anything."
        sub="SiteIQ answers from your own scan data — every claim points back to a signal it measured."
      />

      <div className="mt-14 grid gap-6 lg:mt-20 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
        <Reveal className="panel flex flex-col overflow-hidden">
          <div className="border-border flex items-center gap-2.5 border-b px-5 py-3">
            <Logo mark={18} />
            <span className="label-tech ml-auto">Intelligence Layer · example.com</span>
          </div>

          <div className="flex-1 space-y-6 p-5 md:p-6">
            <div className="flex justify-end">
              <p className="bg-foreground text-background max-w-[80%] rounded-2xl rounded-br-sm px-4 py-2.5 text-sm">
                {question}
              </p>
            </div>

            <div className="flex gap-3">
              <span
                className="mt-1 size-6 shrink-0 rounded-md"
                style={{ background: "var(--gradient-iq)" }}
                aria-hidden="true"
              />
              <div className="min-w-0">
                <p className="text-[0.95rem] leading-relaxed">{current.answer}</p>
                <ul className="mt-4 flex flex-wrap gap-1.5">
                  {current.refs.map((r) => (
                    <li
                      key={r}
                      className="border-border text-muted-foreground rounded-md border px-2 py-1 font-mono text-[0.65rem]"
                    >
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          <form
            onSubmit={(e) => {
              e.preventDefault();
              const match = QUESTIONS.find((q) =>
                q.toLowerCase().includes(draft.trim().toLowerCase()),
              );
              if (draft.trim() && match) setQuestion(match);
              setDraft("");
            }}
            className="border-border flex items-center gap-2 border-t p-3"
          >
            <label htmlFor="ask-siteiq" className="sr-only">
              Ask SiteIQ a question
            </label>
            <input
              id="ask-siteiq"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="Ask about security, performance, SEO…"
              className="placeholder:text-muted-foreground flex-1 bg-transparent px-2 py-2 text-sm outline-none"
            />
            <button
              type="submit"
              aria-label="Send question"
              className="bg-foreground text-background flex size-8 items-center justify-center rounded-md transition-transform duration-200 hover:-translate-y-px"
            >
              <ArrowUp className="size-4" />
            </button>
          </form>
        </Reveal>

        <Reveal delay={120} className="panel p-5">
          <span className="label-tech">Suggested questions</span>
          <ul className="mt-4 space-y-px">
            {QUESTIONS.map((q) => (
              <li key={q}>
                <button
                  type="button"
                  onClick={() => setQuestion(q)}
                  aria-pressed={question === q}
                  className={cn(
                    "border-border w-full border-b py-3 text-left text-sm transition-colors last:border-b-0",
                    question === q ? "text-foreground font-medium" : "text-muted-foreground hover:text-foreground",
                  )}
                >
                  {q}
                </button>
              </li>
            ))}
          </ul>
        </Reveal>
      </div>
    </Section>
  );
}
